### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by gamelaster** [AnaviTech/anavi-soil-moisture-sensor#1] opened 2021-10-30 12:56 UTC
Hi,

I guess that in this repository is old v1.2 resistive sensor.
Please, would it be possible to upload the v1.3 ?

Thanks 😊

**Comment by leon-anavi** [comment] 2021-10-30 14:49
Hi @gamelaster,

Initially in 2017 I created this resistive soil moisture sensor and the first version of ANAVI Gardening uHAT which at that moment was pHAT (uHAT standard hadn't still been announced). Unfortunately there are a lot of disadvantages how resistive sensors work in general. Therefore I put on hold the project for several year and in 2021 ANAVI Gardening uHAT was resigned to support 3rd capacitive soil moisture sensor from other vendors. The result is an open source hardware add-on board for Raspberry Pi designed in KiCad. The schematics are available at this [GitHub repo](https://github.com/AnaviTechnology/anavi-gardening).

Thanks,
Leon

**Comment by leon-anavi** [comment] 2021-10-30 15:49
@gamelaster to avoid any confusion I have just updated README.md to highlight that this project is for a resistive soil moisture sensor and to shortly explain the story as we moved ANAVI Gardening uHAT to capacitive sensors: https://github.com/AnaviTechnology/anavi-soil-moisture-sensor#anavi-resistive-soil-moisture-sensor

Sorry for the confusion caused by the last of enough details in README.md. Thank you for pointing it out. I will close the issue please feel free to open it again.

Best regards,
Leon

**Closed as completed by leon-anavi** 2021-10-30 15:49 UTC

**Comment by gamelaster** [comment] 2021-10-30 15:59
Hi @leon-anavi and thanks for fast reply.

From this I suspect that making custom capacitive moisture sensor is hard. It is really hard or there is another reason for using 3rd party sensor?

Thanks

**Comment by leon-anavi** [comment] 2021-10-30 21:52
Hi @gamelaster,

> From this I suspect that making custom capacitive moisture sensor is hard. It is really hard or there is another reason for using 3rd party sensor?

Yes and no. **Yes**, capacitive moisture sensor is more sophisticated than a resistive sensor but **no** it is still with relative easy design and schematics. Actually, you can find [various open source hardware capacitive soil moisture sensor in Tindie](https://www.tindie.com/search/?q=capacitive+soil+moisture+sensor), including for example https://github.com/Miceuz/i2c-moisture-sensor

There are a couple of major reasons to use a 3rd party sensor:
* Manufacturing low-volume quantities in Plovdiv, Bulgaria, EU is many many times more expensive than using off the shelf sensor module that has been already manufactured in huge quantity by highly automated factories.
* The [global chip shortage](https://en.wikipedia.org/wiki/2020%E2%80%932021_global_chip_shortage) makes sourcing even basic components a challenge.

Regarding these circumstances at the moment it is not worth the risk making another capacitive soil moisture sensor which at the end of the day will not be price competitive and will not bring any technical advantages compared to the existing 3rd party capacitive soil moisture sensors. Btw due to similar price issues this open source hardware resistive soil moisture sensor designed in KiCad hasn't been put for sale although it was designed 4 years ago.

Thanks, Leon
